Repository ReechaKhanal/RoommateSearch, pull requests merged in 2022-04, with the labels that each got.

#171 issue no 170
  .gitignore
  Makefile
  package-lock.json
  package.json
  src/app/footer/footer.component.html
Labels: front-end, Low

#174 Closes #172; Added code in the home component that sends the information to Chat Page
  src/app/home-component/home-component.component.html
  src/app/home-component/home-component.component.ts
Labels: front-end

#175 Closes #173; User Id and Name sent from Home Page is accessed and used in the Chat page
  src/app/chat/chat.component.html
  src/app/chat/chat.component.ts
  src/app/home-component/home-component.component.ts
Labels: Enhancement, front-end, High

#183 Closes #182; WIP #179; Added code not let user navigate from home com…
  server/app.go
  src/app/home-component/home-component.component.ts
Labels: front-end, back-end

#185 Closes #184; Added functionality to let user access profile section o…
  src/app/home-component/home-component.component.ts
  src/app/navbar/navbar.component.ts
Labels: Enhancement, front-end

#186 fixed a bug that would cause errors if a user is not logged in
  src/app/profile/profile.component.html
Labels: bug

#188 Closes #21, Added material location search box
  src/app/app.module.ts
  src/app/home-component/home-component.component.ts
  src/app/location-search/location-search.component.css
  src/app/location-search/location-search.component.html
  src/app/location-search/location-search.component.spec.ts
  src/app/location-search/location-search.component.ts
Labels: Enhancement, front-end

#189 WIP #179; Working on the chat and userid coordination, more work needed
  server/app.go
Labels: back-end

#191 Closes #190; We are now passing in the logged-in user-id along with other information to the chat page
  src/app/chat/chat.component.ts
  src/app/home-component/home-component.component.ts
Labels: back-end

#192 Closes #179; Replaced the randomly generated client-id with already ex…
  server/app.go
Labels: Enhancement, back-end, High

#194 Closes #193; Verified the function of chat using user-id. Removed potential error-causing parts
  src/app/chat/chat.component.ts
  src/app/home-component/home-component.component.ts
Labels: Enhancement, back-end

#195 Closes #113, Added new Address form to sign_up page
  server/models.go
  server/test1.db
  src/app/location-search/location-search.component.css
  src/app/location-search/location-search.component.html
  src/app/location-search/location-search.component.ts
  src/app/sign-up/sign-up.component.css
  src/app/sign-up/sign-up.component.html
  src/app/sign-up/sign-up.component.ts
Labels: front-end, frontend-API-Request

#196 Reversed latitude and logitude to be correct
  src/app/sign-up/sign-up.component.ts
Labels: bug, front-end

#197 WIP #178; A stable version of chat where we have information on Sender, Receipient and Message.
  server/app.go
Labels: back-end, High

#198 Closes #178; The Chat Session is Now Personalized From the Backend
  server/app.go
Labels: back-end, High

#199 #117, added search box and http request to homepage
  src/app/db-connect.service.ts
  src/app/home-component/home-component.component.css
  src/app/home-component/home-component.component.html
  src/app/home-component/home-component.component.ts
Labels: front-end, frontend-API-Request

#200 Closes #117; finished filtering users based on location
  server/app.go
  server/go.mod
  server/go.sum
  server/test1.db
  src/app/home-component/home-component.component.ts
Labels: back-end, API Creation, frontend-API-Request

#201 Fixed a bug where if no valid search location is found, all users are…
  server/app.go
  src/app/home-component/home-component.component.ts
Labels: bug, back-end

#212 Backend
  server/app.go
  server/app_test.go
Labels: back-end, Test
