Repository ReechaKhanal/RoommateSearch, pull requests merged in 2022-02, with the labels that each got.

#68 Closes 66; The address selected by the user can be now converted to Lat and Long
  src/app/app.module.ts
  src/app/map/map.component.css
  src/app/map/map.component.html
  src/app/map/map.component.ts
Labels: Enhancement, front-end

#69 Closes #67, and Starts on # 59; Made login page the landing page and Initial setup for cypress.io
  cypress.json
  cypress/fixtures/example.json
  cypress/integration/1-getting-started/todo.spec.js
  cypress/integration/2-advanced-examples/actions.spec.js
  cypress/integration/2-advanced-examples/aliasing.spec.js
  cypress/integration/2-advanced-examples/assertions.spec.js
  cypress/integration/2-advanced-examples/connectors.spec.js
  cypress/integration/2-advanced-examples/cookies.spec.js
  cypress/integration/2-advanced-examples/cypress_api.spec.js
  cypress/integration/2-advanced-examples/files.spec.js
  cypress/integration/2-advanced-examples/local_storage.spec.js
  cypress/integration/2-advanced-examples/location.spec.js
  cypress/integration/2-advanced-examples/misc.spec.js
  cypress/integration/2-advanced-examples/navigation.spec.js
  cypress/integration/2-advanced-examples/network_requests.spec.js
  cypress/integration/2-advanced-examples/querying.spec.js
  cypress/integration/2-advanced-examples/spies_stubs_clocks.spec.js
  cypress/integration/2-advanced-examples/traversal.spec.js
  cypress/integration/2-advanced-examples/utilities.spec.js
  cypress/integration/2-advanced-examples/viewport.spec.js
  cypress/integration/2-advanced-examples/waiting.spec.js
  cypress/integration/2-advanced-examples/window.spec.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  package-lock.json
  package.json
  src/app/app-routing.module.ts
Labels: front-end, Low, Test

#70 CSS and styling changes to use icons instead of Words, and changing icons, colors and size
  src/app/app.component.css
  src/app/app.module.ts
  src/app/home-component/home-component.component.css
  src/app/home-component/home-component.component.html
  src/app/login/login.component.css
  src/app/login/login.component.html
  src/app/map/map.component.html
  src/app/navbar/navbar.component.css
  src/app/navbar/navbar.component.html
  src/assets/img_Homies_logo.png
Labels: Enhancement, front-end

#71 added email form component in material design
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/email-form/email-form.component.css
  src/app/email-form/email-form.component.html
  src/app/email-form/email-form.component.spec.ts
  src/app/email-form/email-form.component.ts
Labels: Enhancement, front-end

#72 created sign up page, still WIP
  src/app/app.module.ts
  src/app/sign-up/sign-up.component.css
  src/app/sign-up/sign-up.component.html
  src/app/sign-up/sign-up.component.spec.ts
  src/app/sign-up/sign-up.component.ts
Labels: front-end

#76 Added Cypress Tests checking the initial login functionality, and checking the Nav Bar functionality
  cypress/integration/Roomate Search Tests/startup01.js
  cypress/integration/Startup-Login-Signup/startup01.js
  package-lock.json
  package.json
  src/app/navbar/navbar.component.html
Labels: front-end, Test

#78 Input validation for login and sign up
  src/app/app.module.ts
  src/app/login/login.component.html
  src/app/login/login.component.ts
  src/app/sign-up/sign-up.component.css
  src/app/sign-up/sign-up.component.html
  src/app/sign-up/sign-up.component.ts
Labels: front-end

#80 Closes #79; Added a Footer component, styled it and added it all existing pages.
  src/app/app.module.ts
  src/app/chat/chat.component.html
  src/app/footer/footer.component.css
  src/app/footer/footer.component.html
  src/app/footer/footer.component.spec.ts
  src/app/footer/footer.component.ts
  src/app/home-component/home-component.component.html
  src/app/login/login.component.html
  src/app/profile/profile.component.html
Labels: front-end, Low

#82 Closes #81; Changed the current toolbar in the application to Angular material toolbar
  src/app/login/login.component.html
  src/app/navbar/navbar.component.css
  src/app/navbar/navbar.component.html
Labels: Enhancement, front-end, Low, In testing

#83 A change in website theme, testing color schemes that would work better for our project
  package-lock.json
  src/app/app.component.css
  src/app/footer/footer.component.css
  src/app/home-component/home-component.component.css
  src/app/login/login.component.css
  src/app/map/map.component.css
  src/app/map/map.component.html
  src/app/map/map.component.ts
  src/app/navbar/navbar.component.css
  src/app/profile/profile.component.css
Labels: Enhancement, front-end, In testing

#86 Closes #50; finished design of sign up page
  src/app/login/login.component.css
  src/app/login/login.component.html
  src/app/sign-up/sign-up.component.css
  src/app/sign-up/sign-up.component.html
Labels: front-end

#90 login validation, and password hashing
  server/app.go
  server/crypt.go
  server/go.mod
  server/go.sum
  server/models.go
Labels: back-end

#91 Deleting unnecessary lines of code in app component routing
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/home-component/home-component.component.css
  src/app/map/map.component.ts
Labels: Enhancement

#95 Closes #94; Added a broiler plate code for a sidebar in the chat component
  src/app/chat/chat.component.css
  src/app/chat/chat.component.html
  src/app/home-component/home-component.component.html
  src/app/home-component/home-component.component.ts
Labels: front-end

#96 JWT token creation for login
  server/app.go
  server/crypt.go
  server/go.mod
  server/go.sum
Labels: back-end, To be tested

#97 Closes #61; This commit finally sets a connection between home page and chat page.
  src/app/home-component/home-component.component.ts
  src/app/profile/profile.component.html
Labels: front-end, Mid

#98 Styling changes to the application footer
  src/app/chat/chat.component.html
  src/app/footer/footer.component.css
  src/app/footer/footer.component.html
  src/app/home-component/home-component.component.css
  src/app/home-component/home-component.component.html
Labels: Enhancement, front-end

#99 added room status and gender input forms to sign up page
  src/app/app.module.ts
  src/app/sign-up/sign-up.component.css
  src/app/sign-up/sign-up.component.html
  src/app/sign-up/sign-up.component.ts
Labels: front-end

#102 Changed the Startup.js in cypress testing to include the current updates
  cypress/integration/Roomate Search Tests/startup01.js
  src/app/home-component/home-component.component.css
Labels: Test
