Repository ReechaKhanal/RoommateSearch, pull requests merged in 2022-03, with the labels that each got.

#110 Changed Background color for the profile side page, and organized code
  src/app/edit-profile/edit-profile.component.css
  src/app/edit-profile/edit-profile.component.html
  src/app/profile/profile.component.css
  src/app/profile/profile.component.html
Labels: front-end

#112 Closes #111; Made the map/address component more modular
  src/app/home-component/home-component.component.html
  src/app/map/map.component.html
  src/app/map/map.component.ts
  src/app/sign-up/sign-up.component.html
Labels: Enhancement

#125 Closes #124; Added a service (socket.service) to support the chat functionality in the front-end
  src/app/app.module.ts
  src/app/socket.service.spec.ts
  src/app/socket.service.ts
Labels: Enhancement, front-end

#127 Added Application logic to the chat functionality; Closes #126
  src/app/chat/chat.component.css
  src/app/chat/chat.component.html
  src/app/chat/chat.component.ts
Labels: front-end, Mid

#129 updates sign-up api to reflect the format of the database
  server/go.mod
  server/go.sum
  src/app/sign-up/sign-up.component.ts
Labels: API Enhancement

#134 Finished login functionality
  server/test1.db
  src/app/db-connect.service.ts
  src/app/login/login.component.html
  src/app/login/login.component.ts
  src/app/sign-up/sign-up.component.ts
Labels: front-end, frontend-API-Request

#139 Closes #138; Added a way to convert Base64 String back to an image.
  src/app/home-component/home-component.component.html
  src/app/home-component/home-component.component.ts
Labels: front-end, Mid

#141 Changed the Look of the Chat Page,
  src/app/chat/chat.component.html
Labels: Enhancement, front-end

#148 Added upload profile picture or change profile picture feature to the update preferences or the profile-edit page
  src/app/edit-profile/edit-profile.component.html
  src/app/edit-profile/edit-profile.component.ts
Labels: Enhancement, front-end

#150 Displays the user's profile image in home page
  server/test1.db
  src/app/home-component/home-component.component.html
  src/app/home-component/home-component.component.ts
  src/app/sign-up/sign-up.component.ts
Labels: front-end

#151 Closes #116; Added Latitude and Logitude in database schema
  server/models.go
Labels: back-end, database

#152 Added a Radio button to Edit profile page;
  src/app/edit-profile/edit-profile.component.html
  src/app/edit-profile/edit-profile.component.ts
Labels: Enhancement, front-end, Mid

#153 Closes #53; finished JWT functionality
  server/app.go
  server/crypt.go
  server/models.go
  server/test1.db
Labels: back-end, database, API Creation

#157 Closes #143; Added a check to not display the logged in user on the home page
  src/app/db-connect.service.ts
  src/app/home-component/home-component.component.html
  src/app/home-component/home-component.component.ts
Labels: Enhancement, front-end

#163 Started on #162; Added couple of more test files and starter code for each file.
  cypress/integration/Roomate Search Tests/Startup-Login-Signup/ChatPageTest.js
  cypress/integration/Roomate Search Tests/Startup-Login-Signup/HomePageTest.js
  cypress/integration/Roomate Search Tests/Startup-Login-Signup/MyProfilePageTest.js
  cypress/integration/Roomate Search Tests/Startup-Login-Signup/startup01.js
Labels: Mid, Test

#166 Closes #165; Added complete tests for the home page of our application
  cypress/integration/Roomate Search Tests/Startup-Login-Signup/HomePageTest.js
  src/app/home-component/home-component.component.html
  src/app/map/map.component.ts
Labels: Test
